version: "3"

services:
  api.ecommerce.docker:
    container_name: api_ecommerce
    image: api_ecommerce
    user: root
    working_dir: /app/
    restart: always
    ports:
      - 8001:3333
    expose:
      - 8001
    volumes:
      - .:/app
    env_file:
      - ./.docker/api/docker.env
    command: "/./app/.docker/api/start.sh"
