version: "3.9"

services:
  app.sat.docker:
    container_name: ecommerce_api_1.0
    image: ecommerce_api_1.0
    user: root
    working_dir: /app/
    restart: always
    ports:
      - 8001:3333
    expose:
      - 8001
    volumes:
      - .:/app
    env_file:
      - ./.docker/loopback/docker.env
    command: "/./app/.docker/loopback/start.sh"
